### ISSUE TITLE
Cannot use nimble_strftime in Phoenix

### ISSUE THREAD

**Issue by ghost** [plataformatec/nimble_strftime#21]
I get the following error:
`function NimbleStrftime.format/2 is undefined (module NimbleStrftime is not available)`

**Comment by josevalim** [comment]
Did you add it as a dependency? If so, which version is in your mix.lock file?

**Comment by tiotolstoy** [comment]
`  "nimble_strftime": {:hex, :nimble_strftime, "0.1.1", "b988184d1bd945bc139b2c27dd00a6c0774ec94f6b0b580083abd62d5d07818b", [:mix], [], "hexpm"},`

**Comment by tiotolstoy** [comment]
Disregard. I wasn't `mix deps.get` in the correct folder - my structure is very nested. Thanks Jose!
